### ISSUE TITLE
Focus aid is enabled by default

### ISSUE THREAD

**Issue by skronstein** [krontech/chronos-cam-app#134]
Focus aid is enabled by default.  Edges are highlighted, though the checkbox for Focus Aid on the main screen is unchecked.

**Comment by oskirby** [comment]
This is possibly fixed by https://github.com/krontech/chronos-cli/commit/f0450cf3739df83d7fcea268f56084d6248ced0d which resolved some dead code issues when switching from playback to live display.

**Comment by skronstein** [comment]
Bug still present on my camera running software 0.4.0~alpha220.
